# Use the 'docker-compose up' command to run it!

version: '3.8'
services:
  sep4-frontend:
    image: sep4-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sep4-frontend-container
    ports:
      - "4200:4200"
      - "2222:22"
    tty: true
    stdin_open: true
    #environment:
      #- DOCKER_HOST=unix:///var/run/docker.sock
      #- DOCKER_HOST=tcp://localhost:2375