name: Build and Test

on:
  push:
    branches:
#      - main
      - docker-local-development
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        id: build
        run: npm run build
#        continue-on-error: true

      - name: Run tests
        id: test
        run: npm run test
#        continue-on-error: true


#      - name: Notify if build or test failed
#        if: ${{ job.status != 'success' }}
#        uses: appleboy/slack-action@master
#        with:
#          status: ${{ job.status }}
#          text: "The ${{ job.statuses.test == 'failure' && job.statuses.build == 'success' ? 'test' : 'build' }} job failed for ${{ github.repository }}."
#          channel: "#notifications"
#          username: "GitHub Actions"
#          icon_emoji: ":octocat:"