name: Push to Master

on:
  push:
    #branches: [master]
    branches: [docker-local-development]

jobs:
  call-workflow-build-and-test:
    uses: ./.github/workflows/workflow_bases/workflow-build-test.yaml
  call-workflow-deploy:
    needs: call-workflow-build-and-test
    uses: ./.github/workflows/workflow_bases/workflow-deploy.yaml