on:
  push:
    branches:
      - master
      - docker-local-development
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'


      - name: Run a random command
        run: npm build
