name: Build and Test

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:

jobs:
  build:
    runs-on: node:20

    steps:
      - uses: actions/checkout@v2

      #- name: Use Node.js
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: '20'

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install NX
        run: npm install nx

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Run tests
        run: npx nx run-many --target test --all