name: Build and Test

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Netlify CLI
        run: npm install netlify-cli --save-dev

      - name: Build site
        run: npm run build

      - name: Print first 3 characters of Secret
        run: echo $NETLIFY_AUTH_TOKEN | head -c 3
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Deploy Site to Netlify
        run: npx netlify deploy --dir=dist/lizards-inc-fe --prod --site=5f029723-5c0d-4190-a3d6-a04ef2b8e277
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}