name: Build and Test

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Netlify CLI
        run: npm install netlify-cli --save-dev

      - name: Build site
        run: npm run build

      - name: Deploy Site to Netlify
        run: npx netlify deploy --dir=dist/lizards-inc-fe --prod